[profile.default]
solc_version = "0.8.24"
src = "src"
out = "out"
libs = ["lib"]

remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "openzeppelin-contracts/=lib/openzeppelin-contracts/",
  "forge-std/=lib/forge-std/src/",
  "@primuslabs/zktls-contracts/=lib/zktls-contracts/"
]
